---
- name: Create/Update CF Records
  hosts: localhost
  tasks:
    - name: Make the change to Cloudflare
      cloudflare_dns:
          zone: "{{ inventory_hostname }}"
          record: "{{ record }}"
          value: "{{ value }}"
          state: "{{ state }}"
          account_email: "{{ account_email }}"
          account_api_token: "{{ account_api_token }}"